networks:
  restaurant-network:
    name: restaurant-network
    driver: bridge

services:
  restaurant-mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - restaurant-network

  authorization-server:
    image: authorization-server
    command: [ "/wait-for-it.sh", "restaurant-mysql:3306", "-t", "45", "--","java", "-jar", "authorization-server.jar" ]
    environment:
      DATABASE_HOST: restaurant-mysql
    networks:
      - restaurant-network
    depends_on:
      - restaurant-mysql

  api-restaurant:
    image: api-restaurant
    command: [ "/wait-for-it.sh", "authorization-server:9000", "-t", "150", "--","java", "-jar", "api-restaurant.jar" ]
    environment:
      DATABASE_HOST: restaurant-mysql
      AUTH_SERVER_HOST: authorization-server
    networks:
      - restaurant-network
    depends_on:
      - authorization-server

  restaurant-reverse-proxy:
    build: ./nginx
    image: restaurant-reverse-proxy
    ports:
      - "80:80"
    networks:
      - restaurant-network
    depends_on:
      - api-restaurant